version: 0.2
phases:
  install:
    commands:
      - echo installing pulumi packages...
      - aws --version
      - kubectl version --short --client
      - node -v
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.24.7/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - sudo mv ./kubectl /usr/local/bin/kubectl
      - kubectl version --short --client
      - npm install
      - curl -fsSL https://get.pulumi.com | sh -s -- --version 3.51.1
      - export PATH="/root/.pulumi/bin:$PATH"
      - PULUMI_ACCESS_TOKEN=pul-96d741964eb15d37f32a2d02458ea105e9ee052d
      - pulumi login 
      - export PULUMI_CONFIG_PASSPHRASE="somepassfrsa"
      - pulumi stack select --create dev
      - pulumi config set aws:region us-west-2
      - pulumi config set aws:skipMetadataApiCheck false
      - aws configure set region us-east-1 --profile pulumi
      - aws configure set aws_access_key_id AKIATN2OCZL2SQDIAR4G --profile pulumi
      - aws configure set aws_secret_access_key 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 --profile pulumi
      - export AWS_PROFILE=pulumi
      - pulumi config set aws:profile pulumi
  build:
    commands:
      - echo start building...
      - pulumi up --skip-preview
  post_build:
    commands:
      - echo Build completed on `date`
      - printf '[{"name":"VALUE","imageUri":"DDDDD"}]' "'$REPOSITORY_URI:$IMAGE_TAG'" > imagedefinitions.json
artifacts:
    files: imagedefinitions.json